---
title: "Untitled"
author: "Herbert Liu"
date: "5/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(knitr)
opts_knit$set(root.dir ="./IntroCompFinR")
```

```{r}
library(quantmod)
library(IntroCompFinR)
```
```{r}
getSymbols.yahoo("AMZN",
                 .GlobalEnv,
                 return.class = 'xts',
                 index.class  = 'Date',
                 from = "1998-01-01",
                 to = "2021-12-31",
                 periodicity = "daily")
x <- AMZN$AMZN.Adjusted
colnames(x) <- colnames(amznDailyPrices2020)
save(x, file = "./data/amznDailyPrices.rda")
amznDailyPrices2020 <- x
usethis::use_data(amznDailyPrices2020, overwrite = TRUE)
```


```{r}
symb <- c("BA", "COST", "JWN", "MSFT", "SBUX", "^GSPC")
getSymbols.yahoo(symb,
                 .GlobalEnv,
                 return.class = 'xts',
                 index.class  = 'Date',
                 from = "1993-01-01",
                 to = "2021-12-31",
                 periodicity = "daily")
```

```{r}
x <- BA$BA.Adjusted
colnames(x) <- colnames(baDailyPrices2020)
save(x, file = "./data/baDailyPrices.rda")
baDailyPrices2020 <- x
usethis::use_data(baDailyPrices2020, overwrite = TRUE)
```

```{r}
x <- COST$COST.Adjusted
colnames(x) <- colnames(costDailyPrices2020)
save(x, file = "./data/costDailyPrices.rda")
costDailyPrices2020 <- x
usethis::use_data(costDailyPrices2020, overwrite = TRUE)
```
```{r}
x <- JWN$JWN.Adjusted
colnames(x) <- colnames(jwnDailyPrices2020)
save(x, file = "./data/jwnDailyPrices.rda")
jwnDailyPrices2020 <- x
usethis::use_data(jwnDailyPrices2020, overwrite = TRUE)
```
```{r}
x <- MSFT$MSFT.Adjusted
colnames(x) <- colnames(msftDailyPrices2020)
save(x, file = "./data/msftDailyPrices.rda")
msftDailyPrices2020 <- x
usethis::use_data(msftDailyPrices2020, overwrite = TRUE)
```
```{r}
x <- SBUX$SBUX.Adjusted
colnames(x) <- colnames(sbuxDailyPrices2020)
save(x, file = "./data/sbuxDailyPrices.rda")
sbuxDailyPrices2020 <- x
usethis::use_data(sbuxDailyPrices2020, overwrite = TRUE)
```
```{r}
x <- GSPC$GSPC.Adjusted
colnames(x) <- colnames(sp500DailyPrices2020)
save(x, file = "./data/sp500DailyPrices.rda")
sp500DailyPrices2020 <- x
usethis::use_data(sp500DailyPrices2020, overwrite = TRUE)
```
```{r}
getSymbols.yahoo(c("VFINX", "VEURX", "VEIEX", "VBISX", "VPACX"),
                 .GlobalEnv,
                 return.class = 'xts',
                 index.class  = 'Date',
                 from = "1995-01-01",
                 to = "2021-12-31",
                 periodicity = "monthly")
```
```{r}
Vanguard <- c("VEURX", "VEIEX", "VBISX", "VPACX")
```

```{r}
VanguardPrices2020 <- xts(VFINX$VFINX.Adjusted)
names(VanguardPrices2020) <- "vfinx"
for(i in Vanguard){
  temp <- eval(parse(text = i))
  # temp <- to.monthly(temp)
  # head(temp)
  temp <- temp[, ncol(temp)]
  names(temp) <- tolower(i)
  VanguardPrices2020 <- cbind(VanguardPrices2020, temp)
}
save(VanguardPrices2020, file = "./data/VanguardPrices.rda")

usethis::use_data(VanguardPrices2020, overwrite = TRUE)
```







